{% set name = "apache-airflow-providers-http" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-http-{{ version }}.tar.gz
  sha256: d40c8f03ffd9e7be63d292528df49a0719b5f68e737da0f816286571c55dac2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - requests >=2.26.0

test:
  imports:
    - airflow.providers.http
    - airflow.providers.http.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Hypertext Transfer Protocol (HTTP) for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-http/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
